Traceback (most recent call last):
  File "/Users/daynan/anaconda3/envs/onl/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/Users/daynan/anaconda3/envs/onl/lib/python3.7/site-packages/nbclient/client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/daynan/anaconda3/envs/onl/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/daynan/anaconda3/envs/onl/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/daynan/anaconda3/envs/onl/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/Users/daynan/anaconda3/envs/onl/lib/python3.7/site-packages/nbclient/client.py", line 536, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Users/daynan/anaconda3/envs/onl/lib/python3.7/site-packages/nbclient/client.py", line 827, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/daynan/anaconda3/envs/onl/lib/python3.7/site-packages/nbclient/client.py", line 735, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# first, we flatten our array to a 1-d array for the plot
data = dec19arr.flatten()

fig, ax = plt.subplots(figsize=(15,5))
sns.histplot(data, bins=100, label='Per-pixel radiance',legend=True, ax=ax)
plt.legend(fontsize=20)
plt.title('Distribution of VIIRS Nov 2019 nighttime lights (Berlin)', fontsize=20);
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m<ipython-input-3-91069bfaec4a>[0m in [0;36m<module>[0;34m[0m
[1;32m      3[0m [0;34m[0m[0m
[1;32m      4[0m [0mfig[0m[0;34m,[0m [0max[0m [0;34m=[0m [0mplt[0m[0;34m.[0m[0msubplots[0m[0;34m([0m[0mfigsize[0m[0;34m=[0m[0;34m([0m[0;36m15[0m[0;34m,[0m[0;36m5[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 5[0;31m [0msns[0m[0;34m.[0m[0mhistplot[0m[0;34m([0m[0mdata[0m[0;34m,[0m [0mbins[0m[0;34m=[0m[0;36m100[0m[0;34m,[0m [0mlabel[0m[0;34m=[0m[0;34m'Per-pixel radiance'[0m[0;34m,[0m[0mlegend[0m[0;34m=[0m[0;32mTrue[0m[0;34m,[0m [0max[0m[0;34m=[0m[0max[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      6[0m [0mplt[0m[0;34m.[0m[0mlegend[0m[0;34m([0m[0mfontsize[0m[0;34m=[0m[0;36m20[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      7[0m [0mplt[0m[0;34m.[0m[0mtitle[0m[0;34m([0m[0;34m'Distribution of VIIRS Nov 2019 nighttime lights (Berlin)'[0m[0;34m,[0m [0mfontsize[0m[0;34m=[0m[0;36m20[0m[0;34m)[0m[0;34m;[0m[0;34m[0m[0;34m[0m[0m

[0;31mAttributeError[0m: module 'seaborn' has no attribute 'histplot'
AttributeError: module 'seaborn' has no attribute 'histplot'

